# Generated by Django 3.0.6 on 2020-05-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
